### ISSUE TITLE
BT thinks a url has already been added

### ISSUE THREAD

**Issue by khtan** [tconfrey/BrainTool#7] opened 2020-12-12 02:58 UTC
Hi,

I am a new user of BT and have a 2 link BrainTool.org file. When I tried to add a third link, the Choose Tag
dialog tells me that the tab is already under BT control. I attach a picture and copy of BrainTool.org for your considration. Github does not like the .org extension, so I've renamed it BrainTool.txt.

I am using Chrome Version 87.0.4280.88 (Official Build) (64-bit), on Windows 10.

Hopefully, if this is an operator error on my part, someone can point it out to me.

Thanks,

[BrainTool.txt](https://github.com/tconfrey/BrainTool/files/5682383/BrainTool.txt)

![BT-UnableToAddUrl](https://user-images.githubusercontent.com/8535034/101970943-6ea6b980-3be2-11eb-8f05-ff5509ed3ead.png)

**Comment by khtan** [comment] 2020-12-12 04:31
The URL that I was trying to add is : https://ericjscholl.medium.com/trump-makes-clear-the-price-of-joining-his-gang-fd785ddb690b

**Comment by khtan** [comment] 2020-12-12 21:18
I will rephrase my question thus:

The URL is new but somehow BT thinks it has been added already. If you examine the BrainTool.org (.txt) file, you can confirm that the link is new. 
Is there something with BrainTool.org content that is tricking BT into this behavior?

Thanks,

**Comment by tconfrey** [comment] 2021-02-20 22:15
Hi @khtan ,
Sorry for not responding, just seeing this. I hadn't thought to monitor github for issues but will do so from here on!

I released the 0.6 version of BrainTool last month. It had a bunch of fixes for various issues although nothing that sounds exactly like this. I did pull down your test case and was not able to reproduce the issue (screenshot of added link below). Please LMK if you are still having issues, I'd very much like to reproduce and fix it if its still a problem.
Tony 
<img width="528" alt="btscreen" src="https://user-images.githubusercontent.com/5399929/108609878-07a23f80-739f-11eb-9404-b7fd67ffd611.png">

**Comment by khtan** [comment] 2021-02-21 01:34
Thanks Tony for your acknowledgement. It is definitely hard to reproduce. I've moved from a BrainTool centric workflow to a Spacemacs-Org file centric workflow simply because the UI is still new and you have limited resources and have to prioritize which to go after. For example, if there are hundreds of links, it would not be easy to use BrainTool to organize and find. A Spacemacs-Org file centric workflow removes a lot of UI dependencies so that after capturing the link, I can view/reorganize etc in Emacs directly.
So I won't be offended if this request is closed as "Unable to Reproduce".

**Comment by tconfrey** [comment] 2021-03-02 16:01
As suggested by @khtan closing this as unable to reproduce. 

Also @khtan, in developing BrainTool I myself mostly organized the tree structure in emacs. With enthusiastic users who are not emacs-ers I've been improving the ability to work fully in the web ui.  The 0.6 and 0.7 releases improved the ability to add, move and edit tags and links; and the 0.8 version I'm currently working on adds keyboard support. In working with it as I develop I'm really liking the way it feels. Hopefully when I get it released you'll agee!
Tony

**Closed by tconfrey** 2021-03-02 16:01 UTC
